/**
 * @fileoverview gRPC-Web generated client stub for proto.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v0.0.0
// source: proto/v1/api.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../google/api/annotations_pb.js')
const proto = {};
proto.proto = {};
proto.proto.v1 = require('./api_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.v1.AirbotServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.v1.AirbotServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.v1.StartRequest,
 *   !proto.proto.v1.StartResponse>}
 */
const methodDescriptor_AirbotService_Start = new grpc.web.MethodDescriptor(
  '/proto.v1.AirbotService/Start',
  grpc.web.MethodType.UNARY,
  proto.proto.v1.StartRequest,
  proto.proto.v1.StartResponse,
  /**
   * @param {!proto.proto.v1.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.v1.StartResponse.deserializeBinary
);


/**
 * @param {!proto.proto.v1.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.v1.StartResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.v1.StartResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.v1.AirbotServiceClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.v1.AirbotService/Start',
      request,
      metadata || {},
      methodDescriptor_AirbotService_Start,
      callback);
};


/**
 * @param {!proto.proto.v1.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.v1.StartResponse>}
 *     Promise that resolves to the response
 */
proto.proto.v1.AirbotServicePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.v1.AirbotService/Start',
      request,
      metadata || {},
      methodDescriptor_AirbotService_Start);
};


module.exports = proto.proto.v1;

